/**
 * 🎨 Curator's Workbench - Premium Edition
 * 
 * Interactive playlist creation studio featuring:
 * - 3-column grid of liked tracks with rich metadata
 * - Glassmorphism design elements
 * - Robust audio preview with debug logging
 * - Target playlist selector
 * - Smooth animations and haptic feedback
 */

import React, { useState, useCallback, useEffect } from 'react';
import {
    View,
    Text,
    FlatList,
    TouchableOpacity,
    StyleSheet,
    Alert,
    TextInput,
    Modal,
    Pressable,
    ActivityIndicator,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { router } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { useAuthStore } from '../../stores/authStore';
import { useCuratorStore, CuratorTrack } from '../../stores/curatorStore';
import { TrackGridItem, StagingArea, GRID_GAP, GRID_PADDING } from '../../components/curator';
import { Colors } from '../../constants/theme';
import api from '../../services/api';
import audioService, { AudioState } from '../../services/audioService';

// Playlist type for selector
interface Playlist {
    id: string;
    name: string;
    color?: string;
    trackCount?: number;
}

export default function CuratorScreen() {
    const { userData, refreshUserData } = useAuthStore();
    const { stagingTracks, clearStaging } = useCuratorStore();

    // Search & Filter
    const [searchQuery, setSearchQuery] = useState('');
    const [showSearch, setShowSearch] = useState(false);

    // Audio State (managed by audioService)
    const [audioState, setAudioState] = useState<AudioState>({
        isPlaying: false,
        isLoading: false,
        currentTrackId: null,
        error: null,
    });

    // Playlists for selector
    const [playlists, setPlaylists] = useState<Playlist[]>([
        { id: 'new', name: '+ Yeni Liste Oluştur', color: Colors.primary },
    ]);
    const [selectedPlaylist, setSelectedPlaylist] = useState<Playlist | null>(null);

    // Create Playlist Modal
    const [showCreateModal, setShowCreateModal] = useState(false);
    const [playlistName, setPlaylistName] = useState('');
    const [isCreating, setIsCreating] = useState(false);

    // Convert liked tracks to CuratorTrack format
    // Also sanitize previewUrl - convert "undefined" string to actual null
    const tracks: CuratorTrack[] = (userData?.likes || []).map(like => {
        // Sanitize previewUrl - check for invalid string values
        let sanitizedPreviewUrl: string | null = like.previewUrl || null;
        if (sanitizedPreviewUrl === 'undefined' ||
            sanitizedPreviewUrl === 'null' ||
            sanitizedPreviewUrl === '') {
            sanitizedPreviewUrl = null;
        }

        return {
            id: like.trackId,
            name: like.trackName,
            artist: like.artistName || 'Unknown Artist',
            image: like.image,
            previewUrl: sanitizedPreviewUrl,
        };
    });

    // Filtered tracks based on search
    const filteredTracks = searchQuery.trim()
        ? tracks.filter(t =>
            t.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
            t.artist.toLowerCase().includes(searchQuery.toLowerCase())
        )
        : tracks;

    // Fetch user playlists on mount
    useEffect(() => {
        fetchPlaylists();
    }, []);

    // Cleanup audio on unmount
    useEffect(() => {
        return () => {
            audioService.stopAudio();
        };
    }, []);

    // Fetch playlists from API
    const fetchPlaylists = async () => {
        try {
            const response = await api.get('/playlists');
            const userPlaylists = response.data?.playlists || response.data || [];

            // Filter only user-created playlists (exclude system/auto-generated)
            const filteredPlaylists = userPlaylists.filter((p: any) =>
                !p.isSystem && !p.isAutoGenerated
            );

            setPlaylists([
                { id: 'new', name: '+ Yeni Liste Oluştur', color: Colors.primary },
                ...filteredPlaylists.map((p: any) => ({
                    id: p._id || p.id,
                    name: p.name,
                    color: p.color || Colors.gradients.playlists[0],
                    trackCount: p.trackCount || 0,
                })),
            ]);
        } catch (error) {
            console.log('Playlist fetch error:', error);
        }
    };

    /**
     * Play preview using audioService with debug logging
     */
    const handlePlayPreview = useCallback(async (track: CuratorTrack) => {
        // Debug: Log track info
        console.log('🎵 handlePlayPreview called for:', track.name);
        console.log('🎵 Preview URL:', track.previewUrl);

        await audioService.togglePlayback({
            trackId: track.id,
            previewUrl: track.previewUrl,
            onStatusChange: (state) => {
                setAudioState(state);
            },
            onError: (error) => {
                Alert.alert('Önizleme Hatası', error, [{ text: 'Tamam' }]);
            },
            onFinish: () => {
                setAudioState(prev => ({ ...prev, isPlaying: false, currentTrackId: null }));
            },
        });
    }, []);

    // Handle playlist selection
    const handlePlaylistSelect = useCallback((playlist: Playlist | null) => {
        if (playlist?.id === 'new') {
            setShowCreateModal(true);
            setSelectedPlaylist(null);
        } else {
            setSelectedPlaylist(playlist);
        }
    }, []);

    // Finalize playlist
    const handleFinalize = useCallback((tracks: CuratorTrack[]) => {
        if (selectedPlaylist && selectedPlaylist.id !== 'new') {
            // Add to existing playlist
            handleAddToExistingPlaylist(tracks, selectedPlaylist);
        } else {
            // Show create modal
            setShowCreateModal(true);
        }
    }, [selectedPlaylist]);

    // Add tracks to existing playlist
    const handleAddToExistingPlaylist = async (tracks: CuratorTrack[], playlist: Playlist) => {
        setIsCreating(true);
        try {
            for (const track of tracks) {
                await api.post(`/playlists/${playlist.id}/add`, {
                    trackId: track.id,
                    trackName: track.name,
                    image: track.image,
                    previewUrl: track.previewUrl,
                    artistName: track.artist,
                });
            }

            Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
            Alert.alert(
                'Başarılı! 🎉',
                `${tracks.length} şarkı "${playlist.name}" listesine eklendi!`,
                [{
                    text: 'Tamam',
                    onPress: () => {
                        clearStaging();
                        refreshUserData();
                        fetchPlaylists();
                    }
                }]
            );
        } catch (error: any) {
            console.error('Add to playlist error:', error);
            Alert.alert('Hata', error?.response?.data?.error || 'Şarkılar eklenemedi');
        } finally {
            setIsCreating(false);
        }
    };

    // Create new playlist
    const handleCreatePlaylist = useCallback(async () => {
        if (!playlistName.trim()) {
            Alert.alert('Hata', 'Lütfen liste adı girin');
            return;
        }

        setIsCreating(true);
        try {
            // Create playlist
            const createRes = await api.post('/playlists', { name: playlistName.trim() });
            const playlistId = createRes.data?.id || createRes.data?.playlist?.id || createRes.data?._id;

            if (!playlistId) {
                throw new Error('Playlist ID alınamadı');
            }

            // Add tracks to playlist
            for (const track of stagingTracks) {
                await api.post(`/playlists/${playlistId}/add`, {
                    trackId: track.id,
                    trackName: track.name,
                    image: track.image,
                    previewUrl: track.previewUrl,
                    artistName: track.artist,
                });
            }

            Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
            Alert.alert(
                'Başarılı! 🎉',
                `"${playlistName.trim()}" listesi ${stagingTracks.length} şarkı ile oluşturuldu!`,
                [{
                    text: 'Tamam',
                    onPress: () => {
                        setShowCreateModal(false);
                        setPlaylistName('');
                        clearStaging();
                        refreshUserData();
                        fetchPlaylists();
                    }
                }]
            );
        } catch (error: any) {
            console.error('Create playlist error:', error);
            Alert.alert('Hata', error?.response?.data?.error || 'Playlist oluşturulamadı');
        } finally {
            setIsCreating(false);
        }
    }, [playlistName, stagingTracks, clearStaging, refreshUserData]);

    // Render grid item with rich data
    const renderItem = useCallback(({ item }: { item: CuratorTrack }) => (
        <TrackGridItem
            track={item}
            onPlayPreview={handlePlayPreview}
            isPlaying={audioState.currentTrackId === item.id && audioState.isPlaying}
            isLoading={audioState.currentTrackId === item.id && audioState.isLoading}
            isLiked={true} // All tracks in Curator are from likes
        />
    ), [handlePlayPreview, audioState]);

    const keyExtractor = useCallback((item: CuratorTrack) => item.id, []);

    return (
        <SafeAreaView style={styles.safeArea} edges={['top']}>
            {/* Header */}
            <View style={styles.header}>
                <TouchableOpacity
                    style={styles.headerBtn}
                    onPress={() => router.back()}
                    activeOpacity={0.7}
                >
                    <Ionicons name="chevron-back" size={28} color="rgba(255,255,255,0.8)" />
                </TouchableOpacity>

                <View style={styles.headerCenter}>
                    <Text style={styles.headerTitle}>Curator's Workbench</Text>
                    <Text style={styles.headerSubtitle}>{tracks.length} şarkı</Text>
                </View>

                <TouchableOpacity
                    style={styles.headerBtn}
                    onPress={() => setShowSearch(!showSearch)}
                    activeOpacity={0.7}
                >
                    <Ionicons
                        name={showSearch ? 'close' : 'search'}
                        size={22}
                        color="rgba(255,255,255,0.8)"
                    />
                </TouchableOpacity>
            </View>

            {/* Search Bar */}
            {showSearch && (
                <View style={styles.searchContainer}>
                    <Ionicons name="search" size={18} color="#666" />
                    <TextInput
                        style={styles.searchInput}
                        placeholder="Şarkı veya sanatçı ara..."
                        placeholderTextColor="#666"
                        value={searchQuery}
                        onChangeText={setSearchQuery}
                        autoFocus
                    />
                    {searchQuery.length > 0 && (
                        <TouchableOpacity onPress={() => setSearchQuery('')}>
                            <Ionicons name="close-circle" size={18} color="#666" />
                        </TouchableOpacity>
                    )}
                </View>
            )}

            {/* Audio Error Banner */}
            {audioState.error && (
                <View style={styles.errorBanner}>
                    <Ionicons name="warning" size={16} color="#f59e0b" />
                    <Text style={styles.errorText}>{audioState.error}</Text>
                    <TouchableOpacity onPress={() => setAudioState(prev => ({ ...prev, error: null }))}>
                        <Ionicons name="close" size={18} color="#888" />
                    </TouchableOpacity>
                </View>
            )}

            {/* Grid */}
            <FlatList
                data={filteredTracks}
                renderItem={renderItem}
                keyExtractor={keyExtractor}
                numColumns={3}
                contentContainerStyle={styles.gridContent}
                columnWrapperStyle={styles.gridRow}
                showsVerticalScrollIndicator={false}
                ListEmptyComponent={
                    <View style={styles.emptyState}>
                        <Ionicons name="musical-notes-outline" size={64} color="#333" />
                        <Text style={styles.emptyTitle}>
                            {searchQuery ? 'Sonuç bulunamadı' : 'Henüz beğeni yok'}
                        </Text>
                        <Text style={styles.emptySubtitle}>
                            {searchQuery
                                ? 'Farklı bir arama deneyin'
                                : 'Şarkıları beğenmeye başlayın!'
                            }
                        </Text>
                    </View>
                }
            />

            {/* Staging Area */}
            <View style={styles.stagingWrapper}>
                <StagingArea
                    onFinalize={handleFinalize}
                    onTrackPress={handlePlayPreview}
                    playlists={playlists}
                    selectedPlaylist={selectedPlaylist}
                    onPlaylistSelect={handlePlaylistSelect}
                />
            </View>

            {/* Create Playlist Modal */}
            <Modal
                visible={showCreateModal}
                transparent
                animationType="fade"
                onRequestClose={() => setShowCreateModal(false)}
            >
                <Pressable
                    style={styles.modalOverlay}
                    onPress={() => !isCreating && setShowCreateModal(false)}
                >
                    <Pressable style={styles.modalContent} onPress={e => e.stopPropagation()}>
                        <View style={styles.modalHeader}>
                            <LinearGradient
                                colors={[Colors.primary, Colors.primaryDark]}
                                style={styles.modalIcon}
                            >
                                <Ionicons name="musical-notes" size={32} color="#fff" />
                            </LinearGradient>
                            <Text style={styles.modalTitle}>Playlist Oluştur</Text>
                            <Text style={styles.modalSubtitle}>
                                {stagingTracks.length} şarkı eklenecek
                            </Text>
                        </View>

                        <TextInput
                            style={styles.modalInput}
                            placeholder="Playlist adı..."
                            placeholderTextColor="#666"
                            value={playlistName}
                            onChangeText={setPlaylistName}
                            autoFocus
                            maxLength={50}
                            editable={!isCreating}
                        />

                        <View style={styles.modalActions}>
                            <TouchableOpacity
                                style={[styles.modalBtn, styles.modalBtnPrimary]}
                                onPress={handleCreatePlaylist}
                                disabled={isCreating}
                                activeOpacity={0.8}
                            >
                                {isCreating ? (
                                    <ActivityIndicator color="#fff" size="small" />
                                ) : (
                                    <>
                                        <Ionicons name="checkmark" size={20} color="#fff" />
                                        <Text style={styles.modalBtnPrimaryText}>Oluştur</Text>
                                    </>
                                )}
                            </TouchableOpacity>
                            <TouchableOpacity
                                style={[styles.modalBtn, styles.modalBtnSecondary]}
                                onPress={() => setShowCreateModal(false)}
                                disabled={isCreating}
                                activeOpacity={0.8}
                            >
                                <Text style={styles.modalBtnSecondaryText}>İptal</Text>
                            </TouchableOpacity>
                        </View>
                    </Pressable>
                </Pressable>
            </Modal>
        </SafeAreaView>
    );
}

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#0A0A0A',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 12,
        paddingVertical: 10,
    },
    headerBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerCenter: {
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
        letterSpacing: -0.5,
    },
    headerSubtitle: {
        fontSize: 12,
        color: '#888',
        marginTop: 2,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1a1a1a',
        marginHorizontal: 12,
        marginBottom: 10,
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 12,
        gap: 10,
    },
    searchInput: {
        flex: 1,
        fontSize: 15,
        color: '#fff',
    },
    errorBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(245, 158, 11, 0.15)',
        marginHorizontal: 12,
        marginBottom: 10,
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 10,
        gap: 10,
    },
    errorText: {
        flex: 1,
        fontSize: 13,
        color: '#f59e0b',
    },
    gridContent: {
        padding: GRID_PADDING,
        paddingBottom: 8,
    },
    gridRow: {
        gap: GRID_GAP,
        marginBottom: GRID_GAP,
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 60,
    },
    emptyTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
        marginTop: 16,
    },
    emptySubtitle: {
        fontSize: 14,
        color: '#666',
        marginTop: 8,
    },
    stagingWrapper: {
        padding: 12,
        paddingTop: 4,
    },
    // Modal
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.85)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 24,
    },
    modalContent: {
        width: '100%',
        maxWidth: 340,
        backgroundColor: '#1e1e1e',
        borderRadius: 24,
        padding: 24,
    },
    modalHeader: {
        alignItems: 'center',
        marginBottom: 24,
    },
    modalIcon: {
        width: 72,
        height: 72,
        borderRadius: 36,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
    },
    modalTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#fff',
    },
    modalSubtitle: {
        fontSize: 14,
        color: '#888',
        marginTop: 4,
    },
    modalInput: {
        backgroundColor: '#0a0a0a',
        borderWidth: 1,
        borderColor: '#333',
        borderRadius: 14,
        paddingHorizontal: 18,
        paddingVertical: 16,
        fontSize: 17,
        color: '#fff',
        marginBottom: 24,
    },
    modalActions: {
        flexDirection: 'row',
        gap: 12,
    },
    modalBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        borderRadius: 14,
        gap: 8,
    },
    modalBtnPrimary: {
        backgroundColor: Colors.primary,
    },
    modalBtnPrimaryText: {
        fontSize: 17,
        fontWeight: 'bold',
        color: '#fff',
    },
    modalBtnSecondary: {
        backgroundColor: '#333',
    },
    modalBtnSecondaryText: {
        fontSize: 17,
        fontWeight: '600',
        color: '#fff',
    },
});
